import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Component/Header/Header";
import TopHeader from "./Component/Header/TopHeader";
import Foter from "./Component/Foter area/Foter";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "JSON placeholder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopHeader></TopHeader>
        <Header></Header>
        {children}
        <Foter></Foter>
      </body>
    </html>
  );
}
